---
booktitle: Proceedings of Machine Learning Research
shortname: EAIM
year: '2026'
title: Proceedings of Machine Learning Research
volume: '303'
start: &1 2026-01-26
end: 2026-01-26
published: 2026-01-27
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: EAIM2026
month: 0
tex_title: 'Emerging AI Technologies for Music: Towards Controllable, Collaborative,
  and Creative Systems'
cycles: false
bibtex_editor: Herremans, Dorien and Bhandari, Keshav and Roy, Abhinaba and Colton,
  Simon and Barthet, Mathieu
editor:
- given: Dorien
  family: Herremans
- given: Keshav
  family: Bhandari
- given: Abhinaba
  family: Roy
- given: Simon
  family: Colton
- given: Mathieu
  family: Barthet
description: |
  Proceedings of Machine Learning Research
    Held in Singapore, Singapore on 26 January 2026

  Published as Volume 303 by the Proceedings of Machine Learning Research on 27 January 2026.

  Volume Edited by:
    Dorien Herremans
    Keshav Bhandari
    Abhinaba Roy
    Simon Colton
    Mathieu Barthet

  Series Editors:
    Neil D. Lawrence
date_str: 26 Jan
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v303"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v303
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v303
email: ''
conference:
  name: 1st International Workshop on Emerging AI Technologies for Music
  url: https://amaai-lab.github.io/EAIM2026/
  location: Singapore, Singapore
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: Proceedings_cleaned_clean.bib
# Site settings
# Original source:  Proceedings_cleaned_clean.bib
